# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db2429ca383e2802a21c255323b793063be9d82f78b9011a4c6ee84484d9498f069c1e9e69020aef1546591a5c8152cf6fc3f22da7f5b11e06f54417b56875b4

test:
  secret_key_base: efa2a587a219bcc8262842acf3cc7184099445bbc10b6627f11c8c6aa66a6ed390422ee6bcaab467b391a5bf4eeeb84c5c1c362500e64ddb880848d81158a4fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
